codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "40...100"

  status:
    # Learn more at https://docs.codecov.io/docs/commit-status
    project:
      default:
        threshold: 1% # allow this much decrease on project
    changes: false

comment:
  layout: "reach,diff,flags,tree"
  behavior: default # update if exists else create new
  require_changes: true

ignore:
  - "docs"
  - "*.md"
