project_name: ibc-relay
builds:
  - id: darwin-amd64
    main: ./main.go
    binary: rly
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X github.com/icon-project/ibc-relay/v2/cmd.Version={{ .Tag }}
  - id: darwin-arm64
    main: ./main.go
    binary: rly
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X github.com/icon-project/ibc-relay/v2/cmd.Version={{ .Tag }}
  - id: linux-amd64
    main: ./main.go
    binary: rly
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X github.com/icon-project/ibc-relay/v2/cmd.Version={{ .Tag }}
  - id: linux-arm64
    main: ./main.go
    binary: rly
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X github.com/cosmos/relayer/v2/cmd.Version={{ .Tag }}

archives:
  - id: golang-cross
    builds:
      - darwin-amd64
      - darwin-arm64
      - linux-amd64
      - linux-arm64
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    wrap_in_directory: true

checksum:
  name_template: SHA256SUMS-{{.Version}}.txt
  algorithm: sha256

release:
  prerelease: auto
  draft: true
