global:
    api-listen-addr: :5183
    timeout: 10s
    memo: ""
    light-cache-size: 20
chains:
    archway:
        type: wasm
        value:
            key-directory: /home/user/.relayer/keys/localnet
            key: relayWallet
            chain-id: localnet
            rpc-addr: http://localhost:26657
            account-prefix: archway
            keyring-backend: test
            gas-adjustment: 1.5
            gas-prices: 0.025stake
            min-gas-amount: 1000000
            debug: true
            timeout: 20s
            block-timeout: ""
            output-format: json
            sign-mode: direct
            extra-codecs: []
            coin-type: 0
            broadcast-mode: batch
            ibc-handler-address: archway14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9sy85n2u
            first-retry-block-after: 0
            start-height: 0
            block-interval: 6000
    icon:
        type: icon
        value:
            key: ""
            chain-id: ibc-icon
            rpc-addr: http://localhost:9082/api/v3/
            timeout: 30s
            keystore: /home/user/keystore/godWallet.json
            password: gochain
            icon-network-id: 3
            btp-network-id: 1
            btp-network-type-id: 1
            start-height: 0
            ibc-handler-address: cxa1daa337788364a72644860a5097e3eef7a5d416
            first-retry-block-after: 0
            block-interval: 2000
paths:
    icon-archway:
        src:
            chain-id: ibc-icon
            client-id: 07-tendermint-0
            connection-id: connection-0
        dst:
            chain-id: localnet
            client-id: iconclient-0
            connection-id: connection-0
        src-channel-filter:
            rule: ""
            channel-list: []