# https://hub.docker.com/r/ovrclk/akash/tags?page=1&ordering=last_updated
FROM ovrclk/akash:0.10.0

# Set up dependencies
ENV PACKAGES curl make git libc-dev bash gcc linux-headers eudev-dev python3

USER root

# Install minimum necessary dependencies, build Cosmos SDK, remove packages
RUN apk add --no-cache $PACKAGES 

COPY ./akash-setup.sh .

COPY ./valkeys ./setup/valkeys

EXPOSE 26657

ENTRYPOINT [ "./akash-setup.sh" ]
# NOTE: to run this image, docker run -d -p 26657:26657 ./akash-setup.sh {{chain_id}} {{genesis_account}} {{seeds}} {{priv_validator_key_path}}
