basePath: /
consumes:
- application/json
definitions:
  Chain:
    description: Chain represents the necessary data for connecting to and indentifying
      a chain and its counterparites
    properties:
      account-prefix:
        type: string
        x-go-name: AccountPrefix
      chain-id:
        type: string
        x-go-name: ChainID
      gas-adjustment:
        format: double
        type: number
        x-go-name: GasAdjustment
      gas-prices:
        type: string
        x-go-name: GasPrices
      key:
        type: string
        x-go-name: Key
      rpc-addr:
        type: string
        x-go-name: RPCAddr
      trusting-period:
        type: string
        x-go-name: TrustingPeriod
    type: object
    x-go-package: github.com/cosmos/relayer/relayer
  Chains:
    description: Chains is a collection of Chain
    items:
      $ref: '#/definitions/Chain'
    type: array
    x-go-package: github.com/cosmos/relayer/relayer
  Config:
    description: Config represents the config file for the relayer
    properties:
      chains:
        $ref: '#/definitions/Chains'
      global:
        $ref: '#/definitions/GlobalConfig'
      paths:
        $ref: '#/definitions/Paths'
    type: object
    x-go-package: github.com/cosmos/relayer/cmd
  GlobalConfig:
    description: GlobalConfig describes any global relayer settings
    properties:
      api-listen-addr:
        type: string
        x-go-name: APIListenPort
      light-cache-size:
        format: int64
        type: integer
        x-go-name: LightCacheSize
      timeout:
        type: string
        x-go-name: Timeout
    type: object
    x-go-package: github.com/cosmos/relayer/cmd
  Path:
    description: |-
      Path represents a pair of chains and the identifiers needed to
      relay over them
    properties:
      dst:
        $ref: '#/definitions/PathEnd'
      src:
        $ref: '#/definitions/PathEnd'
      strategy:
        $ref: '#/definitions/StrategyCfg'
    type: object
    x-go-package: github.com/cosmos/relayer/relayer
  PathEnd:
    description: |-
      PathEnd represents the local connection identifers for a relay path
      The path is set on the chain before performing operations
    properties:
      chain-id:
        type: string
        x-go-name: ChainID
      channel-id:
        type: string
        x-go-name: ChannelID
      client-id:
        type: string
        x-go-name: ClientID
      connection-id:
        type: string
        x-go-name: ConnectionID
      order:
        type: string
        x-go-name: Order
      port-id:
        type: string
        x-go-name: PortID
      version:
        type: string
        x-go-name: Version
    type: object
    x-go-package: github.com/cosmos/relayer/relayer
  Paths:
    additionalProperties:
      $ref: '#/definitions/Path'
    description: Paths represent connection paths between chains
    type: object
    x-go-package: github.com/cosmos/relayer/relayer
  StrategyCfg:
    description: StrategyCfg defines which relaying strategy to take for a given path
    properties:
      type:
        type: string
        x-go-name: Type
    type: object
    x-go-package: github.com/cosmos/relayer/relayer
  addChainRequest:
    properties:
      account-prefix:
        type: string
        x-go-name: AccountPrefix
      file:
        type: string
        x-go-name: FilePath
      gas-adjustment:
        type: string
        x-go-name: GasAdjustment
      gas-prices:
        type: string
        x-go-name: GasPrices
      key:
        type: string
        x-go-name: Key
      rpc-addr:
        type: string
        x-go-name: RPCAddr
      trusting-period:
        type: string
        x-go-name: TrustingPeriod
      url:
        type: string
        x-go-name: URL
    type: object
    x-go-package: github.com/cosmos/relayer/cmd
  chainStatusResponse:
    properties:
      balance:
        type: boolean
        x-go-name: Balance
      key:
        type: boolean
        x-go-name: Key
      light:
        type: boolean
        x-go-name: Light
      path:
        type: boolean
        x-go-name: Path
    type: object
    x-go-package: github.com/cosmos/relayer/cmd
  editChainRequest:
    properties:
      key:
        type: string
        x-go-name: Key
      value:
        type: string
        x-go-name: Value
    type: object
    x-go-package: github.com/cosmos/relayer/cmd
  versionInfo:
    properties:
      commit:
        type: string
        x-go-name: Commit
      cosmos-sdk:
        type: string
        x-go-name: CosmosSDK
      go:
        type: string
        x-go-name: Go
      version:
        type: string
        x-go-name: Version
    type: object
    x-go-package: github.com/cosmos/relayer/cmd
host: localhost:5183
info:
  description: A REST interface for state queries.
  title: Relayer Rest Server.
  version: 1.0.0
paths:
  /chains:
    get:
      operationId: getChains
      responses:
        "200":
          $ref: '#/responses/getChainsResponse'
      summary: Get chains list.
      tags:
      - Chains
  /chains/{name}:
    delete:
      operationId: deleteChain
      parameters:
      - in: path
        name: name
        required: true
        type: string
        x-go-name: Name
      responses:
        "200":
          $ref: '#/responses/chainResponse'
        "500":
          $ref: '#/responses/errorResponse'
      summary: Delete Chain.
      tags:
      - Chains
    get:
      operationId: getChain
      parameters:
      - in: path
        name: name
        required: true
        type: string
        x-go-name: Name
      responses:
        "200":
          $ref: '#/responses/getChainResponse'
        "400":
          $ref: '#/responses/errorResponse'
      summary: Get single chain details.
      tags:
      - Chains
    post:
      description: file and url parameters in body are optional and can't use both
        at once.
      operationId: addChain
      parameters:
      - in: path
        name: name
        required: true
        type: string
        x-go-name: Name
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/addChainRequest'
        x-go-name: Body
      responses:
        "201":
          $ref: '#/responses/chainResponse'
        "400":
          $ref: '#/responses/errorResponse'
        "500":
          $ref: '#/responses/errorResponse'
      summary: Add a chain.
      tags:
      - Chains
    put:
      operationId: updateChain
      parameters:
      - in: path
        name: name
        required: true
        type: string
        x-go-name: Name
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/editChainRequest'
        x-go-name: Body
      responses:
        "200":
          $ref: '#/responses/chainResponse'
        "400":
          $ref: '#/responses/errorResponse'
        "500":
          $ref: '#/responses/errorResponse'
      summary: Update chain config values.
      tags:
      - Chains
  /chains/{name}/status:
    get:
      operationId: getChainStatus
      responses:
        "200":
          $ref: '#/responses/getChainStatus'
        "400":
          $ref: '#/responses/errorResponse'
      summary: Get status of a chain.
      tags:
      - Chains
  /config:
    get:
      operationId: config
      responses:
        "200":
          $ref: '#/responses/configResponse'
      summary: Get config.
      tags:
      - Config
  /version:
    get:
      operationId: version
      responses:
        "200":
          $ref: '#/responses/versionResponse'
      summary: Get version.
      tags:
      - Version
produces:
- application/json
responses:
  chainResponse:
    description: ""
  configResponse:
    description: ""
    schema:
      $ref: '#/definitions/Config'
  errorResponse:
    description: ""
    schema:
      properties:
        err:
          type: string
          x-go-name: Err
      type: object
  getChainResponse:
    description: ""
    schema:
      $ref: '#/definitions/Chain'
  getChainStatus:
    description: ""
    schema:
      $ref: '#/definitions/chainStatusResponse'
  getChainsResponse:
    description: ""
    schema:
      $ref: '#/definitions/Chains'
  versionResponse:
    description: ""
    schema:
      $ref: '#/definitions/versionInfo'
schemes:
- http
swagger: "2.0"
