#!/bin/bash

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Ensure gopath is set and go is installed
if [[ ! -d $GOPATH ]] || [[ ! -d $GOBIN ]] || [[ ! -x "$(which go)" ]]; then
  echo "Your \$GOPATH is not set or go is not installed,"
  echo "ensure you have a working installation of go before trying again..."
  echo "https://golang.org/doc/install"
  exit 1
fi

GAIA_REPO="$GOPATH/src/github.com/cosmos/gaia"
GAIA_BRANCH=stargate-4
GAIA_DATA="$(pwd)/data"

# ARGS:
# $1 -> local || remote, defaults to remote

# Ensure user understands what will be deleted
if [[ -d $GAIA_DATA ]] && [[ ! "$2" == "skip" ]]; then
  read -p "$0 will delete \$(pwd)/data folder. Do you wish to continue? (y/n): " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
      exit 1
  fi
fi

rm -rf $GAIA_DATA #&> /dev/null
killall gaiad #&> /dev/null

set -e


if [[ -d $GAIA_REPO ]]; then
  cd $GAIA_REPO

  # remote build syncs with remote then builds
  if [[ "$1" == "local" ]]; then
    echo "Using local version of github.com/cosmos/gaia"
    make install &> /dev/null
  else
    echo "Building github.com/cosmos/gaia@$GAIA_BRANCH..."
    if [[ ! -n $(git status -s) ]]; then
      # sync with remote $GAIA_BRANCH
      git fetch --all #&> /dev/null

      # ensure the gaia repository successfully pulls the latest $GAIA_BRANCH
      if [[ -n $(git checkout $GAIA_BRANCH -q) ]] || [[ -n $(git pull origin $GAIA_BRANCH -q) ]]; then
        echo "failed to sync remote branch $GAIA_BRANCH"
        echo "in $GAIA_REPO, please rename the remote repository github.com/cosmos/gaia to 'origin'"
        exit 1
      fi

      # install
      make install &> /dev/null

      # ensure that built binary has the same version as the repo
      if [[ ! "$(gaiad version --long 2>&1 | grep "commit:" | sed 's/commit: //g')" == "$(git rev-parse HEAD)" ]]; then
        echo "built version of gaiad commit doesn't match"
        exit 1
      fi
    else
      echo "uncommited changes in $GAIA_REPO, please commit or stash before building"
      exit 1
    fi

  fi
else
  echo "$GAIA_REPO doesn't exist, and you may not have have the gaia repo locally,"
  echo "if you want to download gaia to your \$GOPATH try running the following command:"
  echo "mkdir -p $(dirname $GAIA_REPO) && git clone git@github.com:cosmos/gaia $GAIA_REPO"
fi

chainid0=ibc0
chainid1=ibc1

echo "Generating gaia configurations..."
mkdir -p $GAIA_DATA && cd $GAIA_DATA && cd ../
./scripts/one-chain $chainid0 ./data 26657 26656 6060 9090
./scripts/one-chain $chainid1 ./data 26557 26556 6061 9091

[ -f $GAIA_DATA/$chainid0.log ] && echo "$chainid0 initialized. Watch file $GAIA_DATA/$chainid0.log to see its execution."
[ -f $GAIA_DATA/$chainid1.log ] && echo "$chainid1 initialized. Watch file $GAIA_DATA/$chainid1.log to see its execution."