name: Create and publish a Docker image

on:
  push:
    tags:
    - '**'
    branches:
    - 'main'
    - '82-run-relay-node-locally-on-pr-merge-to-main'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/relay-node
          tag: latest
