name: Build and Push to DockerHub

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/sagaxyz/*
    steps:
      - name: Set up access to private Go modules
        env:
          GITHUB_USER: ${{ secrets.GH_USER }}
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: git config --global url."https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"
      
      - name: Checkout
        uses: actions/checkout@v3
      -
        name: Git fetch everything
        run: git fetch --prune --unshallow
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: './go.mod'
          cache: true
      - run: go version

      - name: Compile rly
        run : make build
      -
        name: Get Github tag
        id: meta
        run: |
          echo "::set-output name=tag::$(echo ${{github.ref_name}} | sed -e 's/^v//')"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: sagaxyz
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: saga.Dockerfile
          push: true
          build-args: |
            GITHUB_USER=${{ secrets.GH_USER }}
            GITHUB_TOKEN=${{ secrets.GH_ACCESS_TOKEN }}
          platforms: linux/amd64
          tags: sagaxyz/go-relayer:${{ steps.meta.outputs.tag }}, sagaxyz/spc:latest
