name: Run gaiad tests

on: [push]

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    # Install and setup go
    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    # setup docker
    - name: Set up Docker 19.03
      uses: docker-practice/actions-setup-docker@0.0.1    
      with:
        docker-version: 19.03
        docker-channel: stable

      # checkout relayer
    - name: checkout relayer
      uses: actions/checkout@v2
    
    # run tests
    - name: run gaia tests
      run: make test-gaia
