name: Test and coverage

on:
  push:
    tags:
    - '**'
    # branches:
    # - '**'
  pull_request:
    branches:
      - main

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      # Install and setup go
      - name: Set up Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      # setup gopath
      - name: Set PATH
        run: |
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        shell: bash

      # checkout relayer
      - name: checkout relayer
        uses: actions/checkout@v2

      # setup cache
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # unit tests
      - name: run unit tests
        run: make test
        continue-on-error: true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
